{
 "title": "Aeron game",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "← received     sent →" }
   ],
   "targets": [
    {
     "expr": "rate(aeron_total{label=\"Bytes sent\"}[5s])",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "rate(aeron_total{label=\"Bytes received\"}[5s])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "NAKs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "← received     sent →" }
   ],
   "targets": [
    {
     "expr": "rate(aeron_total{label=\"NAKs sent\"}[5s])",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "rate(aeron_total{label=\"NAKs received\"}[5s])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Status messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "← received     sent →" }
   ],
   "targets": [
    {
     "expr": "rate(aeron_total{label=\"Status Messages sent\"}[5s])",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "rate(aeron_total{label=\"Status Messages received\"}[5s])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Heartbeats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "← received     sent →" }
   ],
   "targets": [
    {
     "expr": "rate(aeron_total{label=\"Heartbeats sent\"}[5s])",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "rate(aeron_total{label=\"Heartbeats received\"}[5s])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Positions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aeron_total{label=\"pub-pos (sampled): 1 2098035903 1 aeron:udp?endpoint=224.1.1.1:1234\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "aeron_total{label=\"sub-pos: 3 2098035903 1 aeron:udp?endpoint=224.1.1.1:1234 @0\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "aeron_total{label=\"sub-pos: 6 2098035903 1 aeron:udp?endpoint=224.1.1.1:1234 @241632\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "aeron_total{label=\"sub-pos: 9 2098035903 1 aeron:udp?endpoint=224.1.1.1:1234 @57729504\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Positions lags",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(aeron_total{label=\"sub-pos: 6 2098035903 1 aeron:udp?endpoint=224.1.1.1:1234 @241632\"}, \"label\", \"pos lag slow-fast\", \"label\", \".*\")\n-\nlabel_replace(aeron_total{label=\"sub-pos: 3 2098035903 1 aeron:udp?endpoint=224.1.1.1:1234 @0\"}, \"label\", \"pos lag slow-fast\", \"label\", \".*\")",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Last Heartbeat Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1000 * time() - aeron_total{label=\"client-heartbeat: 0\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "1000 * time() - aeron_total{label=\"client-heartbeat: 2\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "1000 * time() -aeron_total{label=\"client-heartbeat: 5\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "1000 * time() -aeron_total{label=\"client-heartbeat: 10\"}",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}